blank_issues_enabled: false

contact_links:
  - name: "💬 Community Discussions"
    url: https://github.com/ReplicaFlowOSS/replicaflow/discussions
    about: Share ideas, ask questions or start a conversation with the community.
